Controllers/Admin/AdminHomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SWP_template.Models;

namespace SWP_template.Controllers.Admin
{
    public class AdminHomeController : Controller
    {
        public ILogger<AdminHomeController> Logger { get; }

        public AdminHomeController(ILogger<AdminHomeController> logger)
        {
            Logger = logger;
        }
        public IActionResult AdminHome()
        {

            return View("~/Views/Admin/AdminHome.cshtml");
        }
        public IActionResult ManageUserAccount()
        {
            return View("~/Views/Admin/ManageUserAccount.cshtml", EFManage.GetAllUserAccount());
        }
        public IActionResult RemoveUserAccount(string UserID)
        {
            RemoveUserAccount(UserID);
            return View("~/Views/Admin/ManageUserAccount.cshtml", EFManage.GetAllUserAccount());
        }
    }
}

Controllers/Admin/AdminLoginController.cs
using Microsoft.AspNetCore.Mvc;
using SWP_template.Models;

namespace SWP_template.Controllers.Admin
{
    public class AdminLoginController : Controller
    {
        public IActionResult AdminLogin()
        {
            return View("~/Views/Admin/AdminLogin.cshtml");
        }
        [HttpPost]
        public IActionResult Login(string account, string password, bool rememberme)
        {
            var data = EFManage.Login(account, password, "R001");
            if (data != null)
            {
                IHttpContextAccessor Accessors = new HttpContextAccessor();
                Accessors.HttpContext.Session.SetString("Username", account);
                Accessors.HttpContext.Session.SetString("ID", data.AccountId);
                return RedirectToAction("AdminHome", "AdminHome");
            }
            else
            {
                ViewBag.LoginFail = "Wrong username or password!";
                return View("/Views/Admin/AdminLogin.cshtml");
            }
        }
    }
}

Controllers/Admin/AdminSignupController.cs
using Microsoft.AspNetCore.Mvc;
using ServiceStack;
using SWP_template.Models;

namespace SWP_template.Controllers.Admin
{
    public class AdminSignupController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult AdminSignup()
        {
            return View("~/Views/Admin/AdminSignup.cshtml");
        }
        [HttpPost]
        public IActionResult AdminSignup(string name, string account, string email, string password, string confirmPassword)
        {
            if (ModelState.IsValid)
            {
                Swp1Context context = new Swp1Context();
                if (account.IsEmpty() || email.IsEmpty() || password.IsEmpty() || confirmPassword.IsEmpty())
                {
                    ViewBag.fail = "Please fill required fields";
                    return View("~/Views/Admin/AdminSignup.cshtml");
                }
                else
                if (context.Accountsses.Where(a => a.Username.Equals(account) && a.RoleId.Equals("R001")).FirstOrDefault() != null)
                {
                    ViewBag.fail = "Account existed";
                    return View("~/Views/Admin/AdminSignup.cshtml");
                }
                else if (context.Accountsses.Where(a => a.Email.Equals(email) && a.RoleId.Equals("R001")).FirstOrDefault() != null)
                {
                    ViewBag.fail = "Email existed";
                    return View("~/Views/Admin/AdminSignup.cshtml");
                }
                else
                if (!password.Equals(confirmPassword))
                {
                    ViewBag.fail = "Password and Repeat password is not the same!";
                    return View("~/Views/Admin/AdminSignup.cshtml");
                }
                else
                {
                    EFManage.SinupAccount(name, account, email, password, "R001");
                    return View("~/Views/Admin/AdminLogin.cshtml");
                }
            }
            else return View("~/Views/Admin/AdminSignup.cshtml");
        }

    }
}

Views/Admin/AdminHome.cshtml
@page
@model SWP_template.Views.Owner.PropertiesModel
@inject IHttpContextAccessor Accessors
@using SWP_template.Models


<!-- Main Content -->
<div id="content">

    <!-- Topbar -->
    <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

        <!-- Sidebar Toggle (Topbar) -->
        <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
            <i class="fa fa-bars"></i>
        </button>

        <!-- Topbar Navbar -->
        <ul class="navbar-nav ml-auto">

            <!-- Nav Item - Search Dropdown (Visible Only XS) -->
            <li class="nav-item dropdown no-arrow d-sm-none">
                <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button"
                   data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="fas fa-search fa-fw"></i>
                </a>
                <!-- Dropdown - Messages -->
                <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in"
                     aria-labelledby="searchDropdown">
                    <form class="form-inline mr-auto w-100 navbar-search">
                        <div class="input-group">
                            <input type="text" class="form-control bg-light border-0 small"
                                   placeholder="Search for..." aria-label="Search"
                                   aria-describedby="basic-addon2">
                            <div class="input-group-append">
                                <button class="btn btn-primary" type="button">
                                    <i class="fas fa-search fa-sm"></i>
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </li>

            <div class="topbar-divider d-none d-sm-block"></div>

            <!-- Nav Item - User Information -->
            <li class="nav-item dropdown no-arrow">
                <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                   data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <span class="mr-2 d-none d-lg-inline text-gray-600 small">@Accessors.HttpContext.Session.GetString("Username")</span>
                    <img class="img-profile rounded-circle"
                         src="~/img/user.png">
                </a>
                <!-- Dropdown - User Information -->
                <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                     aria-labelledby="userDropdown">
                    <a class="dropdown-item" href="@Url.ActionLink("OwnerProfile","OwnerHome", new { id = Accessors.HttpContext.Session.GetString("ID")})">
                        <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                        Profile
                    </a>
                    @* <a class="dropdown-item" href="#">
                    <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                    Settings
                    </a>
                    <a class="dropdown-item" href="#">
                    <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
                    Activity Log
                    </a>*@
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                        <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                        Logout
                    </a>
                </div>
            </li>

        </ul>

    </nav>
    <!-- End of Topbar -->
    <!-- Begin Page Content -->
    <div class="container-fluid">

        <!-- Page Heading -->
        <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-gray-800">Dashboard</h1>

        </div>

        <!-- Content Row -->
        <div class="row">

            <!-- Earnings (Monthly) Card Example -->
            <div class="col-xl-3 col-md-6 mb-4">
                <div class="card border-left-primary shadow h-100 py-2">
                    <div class="card-body">
                        <div class="row no-gutters align-items-center">
                            <div class="col mr-2">
                                <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                                    Earnings (Monthly)
                                </div>
                                <div class="h5 mb-0 font-weight-bold text-gray-800">@ViewBag.monthlyIncome VND</div>
                            </div>
                            <div class="col-auto">
                                <i class="fas fa-calendar fa-2x text-gray-300"></i>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <!-- Earnings (Monthly) Card Example -->
            <div class="col-xl-3 col-md-6 mb-4">
                <div class="card border-left-success shadow h-100 py-2">
                    <div class="card-body">
                        <div class="row no-gutters align-items-center">
                            <div class="col mr-2">
                                <div class="text-xs font-weight-bold text-success text-uppercase mb-1">
                                    Earnings (Annual)
                                </div>
                                <div class="h5 mb-0 font-weight-bold text-gray-800">@ViewBag.totalIncome VND</div>
                            </div>
                            <div class="col-auto">
                                <i class="fas fa-dollar-sign fa-2x text-gray-300"></i>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <!-- Earnings (Monthly) Card Example -->
            <div class="col-xl-3 col-md-6 mb-4">
                <div class="card border-left-info shadow h-100 py-2">
                    <div class="card-body">
                        <div class="row no-gutters align-items-center">
                            <div class="col mr-2">
                                <div class="text-xs font-weight-bold text-info text-uppercase mb-1">
                                    Average Stay Time
                                </div>
                                <div class="row no-gutters align-items-center">
                                    <div class="col-auto">
                                        <div class="h5 mb-0 mr-3 font-weight-bold text-gray-800">@ViewBag.datediff day(s)</div>
                                    </div>

                                </div>
                            </div>
                            <div class="col-auto">
                                <i class="fas fa-home fa-2x text-gray-300"></i>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <!-- Pending Requests Card Example -->
            <div class="col-xl-3 col-md-6 mb-4">
                <div class="card border-left-warning shadow h-100 py-2">
                    <div class="card-body">
                        <div class="row no-gutters align-items-center">
                            <div class="col mr-2">
                                <div class="text-xs font-weight-bold text-warning text-uppercase mb-1">
                                    Average Demographic
                                </div>
                                <div class="h5 mb-0 font-weight-bold text-gray-800">@ViewBag.booker</div>
                            </div>
                            <div class="col-auto">
                                <i class="fas fa-user fa-2x text-gray-300"></i>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Content Row -->

        <div class="row">

            <!-- Area Chart -->
            <div class="col-xl-12 col-lg-12">
                <div class="card shadow mb-4">
                    <!-- Card Header - Dropdown -->
                    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                        <h6 class="m-0 font-weight-bold text-primary">Order Overview</h6>
                    </div>
                    <!-- Card Body -->
                    <div class="card-body">
                        <div class="chart-area" style="height: 610px">
                            <canvas id="myBarCharts" style="height: 580px; width:1570px"></canvas>
                            @*<canvas id="myChart" style="max-height:360px"></canvas>*@

                        </div>
                    </div>
                </div>
            </div>
            <!-- Content Row -->
        </div>
        <!-- /.container-fluid -->
        @*  <div class="row">
        <canvas id="myChart" style="width:100%;max-width:600px"></canvas>
        </div>*@
    </div>
    <!-- End of Main Content -->
   @* @section script{
        <script>


            //$(document).ready(function () {
            //    $.getJSON('/OwnerHome/SelectOrdersByMonth1', function (resp) {
            //        console.log(resp);
            //        //RegisterChartOrder(resp);
            //    });
            //});


            // function RegisterChartOrder(lstData){
            //var lb = [];
            //var val = [];
            //$.each(lstData, function(index, item){
            //    lb.push(index+1)
            //    val.push(item[index])
            //    console.log(resp);

            //});

            const xValues = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"];
            const yValues = [@ViewBag.thang1, @ViewBag.thang2, @ViewBag.thang3, @ViewBag.thang4, @ViewBag.thang5, @ViewBag.thang6, @ViewBag.thang7, @ViewBag.thang8, @ViewBag.thang9, @ViewBag.thang10, @ViewBag.thang11, @ViewBag.thang12 ];
            const barColors = ["red", "green", "blue", "orange", "brown"];

            new Chart("myBarCharts", {
                type: "bar",
                data: {
                    labels: xValues,
                    datasets: [{
                        backgroundColor: "blue",
                        data: yValues,
                    }]
                },
                options: {
                    legend: { display: false },
                    title: {
                        display: true,
                        text: "Total orders in year"
                    }
                }
            });
                                  //  }


        </script>
    }
*@

Views/Admin/AdminLogin.cshtml
@{Layout = null;}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>SB Admin 2 - Login</title>

    <!-- Custom fonts for this template-->
    <link href="~/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
          rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="~/css/sb-admin-2.min.css" rel="stylesheet">

</head>

<body class="bg-gradient-primary">

    <div class="container">

        <!-- Outer Row -->
        <div class="row justify-content-center">

            <div class="col-xl-10 col-lg-12 col-md-9">

                <div class="card o-hidden border-0 shadow-lg my-5">
                    <div class="card-body p-0">
                        <!-- Nested Row within Card Body -->
                        <div class="row">
                            <div class="col-lg-6 d-none d-lg-block bg-login-image"></div>
                            <div class="col-lg-6">
                                <div class="p-5">
                                    <div class="text-center">
                                        <h1 class="h4 text-gray-900 mb-4">Welcome Back!</h1>
                                    </div>
                                    <form asp-controller="AdminLogin" asp-action="Login" method="post">
                                        <label>Account</label>
                                        <div class="form-group">
                                            <input type="text" class="form-control form-control-user"
                                                   id="exampleInputEmail" aria-describedby="emailHelp"
                                                   placeholder="Enter Account" name="account" required>
                                        </div>
                                        <label>Password</label>
                                        <div class="form-group">
                                            <input type="password" class="form-control form-control-user"
                                                   id="exampleInputPassword" placeholder="Password" name="password" required>
                                        </div>
                                        <div class="form-group">
                                            <div class="custom-control custom-checkbox small">
                                                <input type="checkbox" class="custom-control-input" id="customCheck">
                                                <label class="custom-control-label" for="customCheck">
                                                    Remember
                                                    Me
                                                </label>
                                            </div>
                                        </div>
                                        <button type="submit" class="btn btn-primary btn-user btn-block">
                                            Login
                                        </button>
                                    </form>
                                    <hr>
                                    <div class="text-center">
                                        <a class="small" href="forgot-password.html">Forgot Password?</a>
                                    </div>
                                    <div class="text-center">
                                        <a class="small" href="@Url.Action("AdminSignup","AdminSignup")">Create an Account!</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>

        </div>

    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="js/sb-admin-2.min.js"></script>

</body>

</html>

Views/Admin/AdminSignup.cshtml
@{
    Layout = null;
}
@using SWP_template.Models
@model RegisterViewModel

<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>SB Admin 2 - Register</title>

    <!-- Custom fonts for this template-->
    <link href="~/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
          rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="~/css/sb-admin-2.min.css" rel="stylesheet">

</head>

<body class="bg-gradient-primary">

    <div class="container">

        <div class="card o-hidden border-0 shadow-lg my-5">
            <div class="card-body p-0">
                <!-- Nested Row within Card Body -->
                <div class="row">
                    <div class="col-lg-5 d-none d-lg-block bg-register-image"></div>
                    <div class="col-lg-7">
                        <div class="p-5">
                            <div class="text-center">
                                <h1 class="h4 text-gray-900 mb-4">Create an Admin Account!</h1>
                            </div>
                            <h5 class="text-danger">@ViewBag.fail</h5>
                            <form asp-controller="AdminSignup" asp-action="AdminSignup" method="post">
                                <div class="form-group">
                                        @Html.LabelFor(m => m.Name, new { @class = "sr-only",@for = "Name" })
                                        @Html.TextBoxFor(m => m.Name, new { @class = "form-control name",id = "name", name = "name",placeholder ="Name", autofocus ="", required="required" })
                                        @Html.ValidationMessageFor(m => m.Name, "", new { @class = "text-danger" })
                                </div>
                                <div class="form-group">
                                   @* <input type="email" class="form-control form-control-user" id="exampleInputEmail"
                                           placeholder="Email Address">*@
                                    @Html.LabelFor(m => m.Account, new { @class = "sr-only",@for = "inputAccount" })
                                    @Html.TextBoxFor(m => m.Account, new { @class = "form-control form-control-user",id = "inputAccount", name = "account",placeholder ="User account", autofocus ="", required="required" })
                                    @Html.ValidationMessageFor(m => m.Account, "", new { @class = "text-danger" })
                                </div>
                                <div class="form-group">
                                    @Html.LabelFor(m => m.Email, new { @class = "sr-only", @for = "inputEmail" })
                                    @Html.TextBoxFor(m => m.Email, new { @class = "form-control email", id = "inputEmail" , name = "email", placeholder = "Email address", autofocus = "" , type = "email", required="required"})
                                    @Html.ValidationMessageFor(m => m.Email, "", new { @class = "text-danger" })
                                </div>
                                <div class="form-group row">
                                    <div class="col-sm-6 mb-3 mb-sm-0">
                                       @* <input type="password" class="form-control form-control-user"
                                               id="exampleInputPassword" placeholder="Password">*@
                                        @Html.LabelFor(m => m.Password, new { @class = "sr-only", @for = "inputPassword" })
                                        @Html.PasswordFor(m => m.Password, new { @class = "form-control form-control-user", id = "inputPassword",name = "Password", placeholder = "Password", type="password", required="required" })
                                        @Html.ValidationMessageFor(m => m.Password)
                                    </div>
                                    <div class="col-sm-6">
                                        @Html.LabelFor(m => m.ConfirmPassword, new { @class = "sr-only", @for = "inputPassword" })
                                        @Html.PasswordFor(m => m.ConfirmPassword, new { @class = "form-control form-control-user",
                                        id = "inputPassword", name = "ConfirmPassword", placeholder = "Confirm Password", type="password" , required="required"})
                                        @Html.ValidationMessageFor(m => m.ConfirmPassword)
                                    </div>
                                </div>


                                <button type="submit" class="btn btn-primary btn-user btn-block">
                                    Register Account
                                </button>

                            </form>

                            <hr>
                            <div class="text-center">
                                <a class="small" href="forgot-password.html">Forgot Password?</a>
                            </div>
                            <div class="text-center">
                                <a class="small" href="@Url.Action("AdminLogin","AdminLogin")">Already have an account? Login!</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="~/vendor/jquery/jquery.min.js"></script>
    <script src="~/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="~/vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="~/js/sb-admin-2.min.js"></script>

</body>

</html>

Views/Admin/ManageUserAccount.cshtml
@model List<SWP_template.Models.Accountss>
@inject IHttpContextAccessor Accessors
@{
    string accountId = @Accessors.HttpContext.Session.GetString("ID");
}


@*<div id="top-bar" class="tb-text-white">
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <div id="links">
                    <ul class="list-unstyled list-inline" style="display: flex; margin-right: 0px !important;">
                        <li>
                            <button class="btn-orange" id="Create" onclick="location.href='@Url.Action("CreateHotel", "CRUDHotel")'">Create</button>
                        </li>

                    </ul>

                </div><!-- end links -->
            </div><!-- end columns -->
        </div><!-- end row -->
    </div><!-- end container -->
</div><!-- end top-bar -->*@

<h4>@ViewBag.mess</h4>
@if (Model != null && Model.Count > 0)
{
    @foreach (var user in Model)
    {
        <div class="user-list">
            <ul class="user-list-left">

                <div class="user-info" style="width: 1000px">

                    <div class="dropdown no-arrow" style="margin-left:945px">
                        <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink"
                           data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in"
                             aria-labelledby="dropdownMenuLink">
                            <div class="dropdown-header">Actions:</div>

                         @*   <a class="dropdown-item" href="@Url.ActionLink("EditHotel","CRUDHotel",new{HotelId = @user.HotelId})">Update</a>
                            <a class="dropdown-item" href="@Url.ActionLink("OwnerHomeRoom","OwnerHome",new{HotelId = @user.HotelId})">Details</a>
                            <div class="dropdown-divider"></div>*@
                            <a class="dropdown-item" href="@Url.ActionLink("DeleteHotelConfirmed","CRUDHotel",new{UserID = @user.AccountId})">Remove</a>
                        </div>
                    </div>
                    <h3 style="width: 70%; margin-left: 30px;">@user.AccountId</h3>
                    <p style=" margin-left: 30px;">@user.Name</p>

                </div>
            </ul>

        </div>
    }
}
else
{
    <h2>No User Found!</h2>
}